//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string nickname { get; set; }
        public string pwd { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string mylike { get; set; }
        public string name { get; set; }
        public string gay { get; set; }
        public string love { get; set; }
        public string blood { get; set; }
        public string blog { get; set; }
        public string myself { get; set; }
        public string qq { get; set; }
        public string msn { get; set; }
        public string state { get; set; }
        public string face { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
