//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class weibo
    {
        public int id { get; set; }
        public string text { get; set; }
        public string images { get; set; }
        public Nullable<int> sendman { get; set; }
        public Nullable<System.DateTime> sendtime { get; set; }
        public Nullable<int> transpond { get; set; }
        public Nullable<int> remark { get; set; }
        public Nullable<int> nice { get; set; }
    }
}
